[build]
builder = "NIXPACKS"

[build.phases]
# Commande explicite pour installer TOUTES les dépendances, y compris devDependencies
install = { cmds = ["npm install"] }
# Commande explicite pour lancer le build après l'installation
build = { cmds = ["npm run build"] }

[deploy]
# La commande de démarrage est définie dans package.json ("start")
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
# Indique à Nixpacks de travailler exclusivement dans le dossier /server
rootDirectory = "server"
numReplicas = 1
containerSize = "2x"

[variables]
PORT = "3000"
MONGODB_URI = "mongodb+srv://businessconnect:tlIQzehUEZnFPwoa@cluster0.gtehtk.mongodb.net/businessconnect?retryWrites=true&w=majority"
JWT_SECRET = "fc5c01210b133afeb2c293bfd28c59df3bb9d3b272999be0eb838c930b1419fd"
JWT_EXPIRES_IN = "7d"

# Configuration Brevo (anciennement Sendinblue)
SMTP_HOST = "smtp-relay.brevo.com"
SMTP_PORT = "587"
SMTP_SECURE = "false"
SMTP_USER = "88ccee002@smtp-brevo.com"
SMTP_PASSWORD = "myFchwr5H6AYtJdq"
SMTP_FROM = "88ccee002@smtp-brevo.com"

# Configuration PayTech
PAYTECH_API_KEY = "be2b2e9b3a0ed01d69d30dff8a21f05199e2e71968788b4890690d7af56ba32b"
PAYTECH_WEBHOOK_SECRET = "6860a504cc73992c2e8dc623c7b31d948ef5a4ec2507a0a4771e62755cca9277"
PAYTECH_BASE_URL = "https://paytech.sn"

# URLs de l'application
CLIENT_URL = "https://app.businessconnectsenegal.com"
API_URL = "https://api.businessconnectsenegal.com" 