[phases.setup]
nixPkgs = ['nodejs-18_x', 'python3', 'gcc', 'make']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['npm ci', 'npm run build']

[start]
cmd = 'node dist/index.js'

[env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error'

[phases.setup.env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error' 