[phases.setup]
nixPkgs = ['nodejs-18_x', 'python3', 'gcc', 'make', 'gnumake']
aptPkgs = ['ca-certificates', 'curl', 'gnupg']

[phases.install]
cmds = [
    'cd server',
    'npm config set registry https://registry.npmjs.org/',
    'npm config set fetch-retries 5',
    'npm config set network-timeout 300000',
    'npm ci --only=production --no-audit --no-fund --prefer-offline'
]

[phases.build]
cmds = [
    'cd server',
    'npm ci --no-audit --no-fund --prefer-offline',
    'npm run build'
]

[start]
cmd = 'cd server && node --max-old-space-size=2048 dist/index.js'

[env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error'
NPM_CONFIG_FETCH_RETRIES = '5'
NPM_CONFIG_REGISTRY = 'https://registry.npmjs.org/'
NPM_CONFIG_NETWORK_TIMEOUT = '300000'
PORT = '3000'

[phases.setup.env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error'
NPM_CONFIG_REGISTRY = 'https://registry.npmjs.org/'
NPM_CONFIG_NETWORK_TIMEOUT = '300000' 