[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'gcc', 'python3']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'yarn start'

[variables]
NODE_ENV = 'production' 