[providers]
node = true

[phases.setup]
nixPkgs = ['nodejs-18_x', 'python3', 'gcc', 'make']

[phases.install]
cmds = [
    'cd server',
    'npm ci --only=production'
]

[phases.build]
cmds = [
    'cd server',
    'npm run build'
]

[start]
cmd = 'cd server && node --max-old-space-size=2048 dist/index.js'

[env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error'

[phases.setup.env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error'
NPM_CONFIG_REGISTRY = 'https://registry.npmjs.org/'
NPM_CONFIG_NETWORK_TIMEOUT = '300000' 