# Spécifie les paquets système nécessaires pour la compilation de certaines dépendances
[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "gcc", "make"]

# Définit la commande de build, Nixpacks se chargera de l'installation des dépendances
[phases.build]
cmds = ["npm run build --prefix server"]

# Définit la commande de démarrage
[start]
cmd = "npm start --prefix server"

[env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error'

[phases.setup.env]
NODE_ENV = 'production'
NODE_OPTIONS = '--max-old-space-size=2048'
NPM_CONFIG_LOGLEVEL = 'error'
NPM_CONFIG_REGISTRY = 'https://registry.npmjs.org/'
NPM_CONFIG_NETWORK_TIMEOUT = '300000' 