services:
  - type: web
    name: businessconnect-api
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://businessconnect:tlIQzehUEZnFPwoa@cluster0.gtehtk.mongodb.net/businessconnect?retryWrites=true&w=majority
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://app.businessconnectsenegal.com
      - key: API_URL
        value: https://api.businessconnectsenegal.com

  - type: web
    name: businessconnect-client
    env: node
    region: frankfurt
    buildCommand: cd businessconnect-senegal/client && npm install && npm run build
    startCommand: cd businessconnect-senegal/client && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://api.businessconnectsenegal.com

databases:
  - name: businessconnect-mongodb
    type: mongodb
    ipAllowList: [] 