# Spécifie les variables d'environnement pour l'environnement de BUILD
# C'est ici que nous forçons l'utilisation de NPM au lieu de Bun.
envVars:
  - key: RENDER_PACKAGE_MANAGER
    value: npm

services:
  - type: web
    name: businessconnect-backend
    env: node
    rootDir: server
    plan: free
    # On sépare clairement l'installation et le build
    buildCommand: |
      npm install
      npm install -g rimraf typescript
      npm run build
    startCommand: "npm start"
    healthCheckPath: /api/health
    envVars:
      # Variables d'environnement pour l'environnement d'exécution (RUN)
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        # Important: Collez votre URL de base de données Supabase ici
        value: "postgresql://postgres.rvflbgylqjhnworrjjis:Qi6DqS4LA2025@aws-0-eu-central-1.pooler.supabase.com:5432/postgres"
      # --- Ajoutez vos autres secrets (JWT_SECRET, etc.) dans l'UI de Render ---
      # Exemple:
      # - key: JWT_SECRET
      #   generateValue: true # Render peut générer un secret pour vous
      # - key: GOOGLE_CLOUD_PROJECT_ID
      #   value: "votre-id-gcp" 