services:
  - type: web
    name: businessconnect-senegal-api
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

  - type: web
    name: businessconnect-senegal
    env: docker
    rootDir: businessconnect-senegal/client
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://businessconnect-senegal2025.onrender.com
    autoDeploy: true 