services:
  - type: web
    name: businessconnect-senegal
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 