[build]
# Nous utilisons Nixpacks, le builder natif de Railway, au lieu de Docker.
builder = "NIXPACKS"

[deploy]
# La commande pour construire votre projet, trouvée dans package.json
buildCommand = "npm run build"
# La commande pour démarrer le serveur une fois construit
startCommand = "node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production" 